version: '3.8'

services:
  mindsdb:
    image: mindsdb/mindsdb
    container_name: mindsdb_container
    ports:
      - "47334:47334" 
      - "47335:47335" 
    volumes:
      - ./mdb_data:/root/mdb_storage 
    environment:
      - MKL_SERVICE_FORCE_INTEL=1 
    restart: unless-stopped

